version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: yarn test --coverage --ci --reporters=default --reporters=jest-junit --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test-results/jest'
      - run:
          name: Lint
          command: yarn lint

      - run: yarn pack -f clio-ts.tgz

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage

      - store_artifacts:
          path: clio-ts.tgz
